---
title: "pstat131-datamemo#1"
author: "Sissi Shen"
date: "2022-10-03"
output: html_document
---

Overview of the dataset:\
\
As a political science and data science double major, I'm excited to apply moduling knowledge to solving political problems. There's a paper that I read in my political science seminar last quarter that discusses the correlation of immigrants background and their possibility of being naturalized through referendums in Switzerland. The voters (Switzerland citizens) would receive leaflets about each immigrant's background, and they would vote to determine whether the immigrant could be naturalized and become a citizen. The findings suggest that the countries of origin of the immigrants have a strong correlation with the result, as people from (former) Yugoslavia and Turkey are less likely to be naturalized. This inspires me to build a classification ML model to predict which immigrant can be naturalized based on their profiles.\
A replication of data can be found on Harvard Dataverse here: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/T8OYHT \
However, it requires access data access through Federal Statistics Office in Switzerland, so I'm trying to approach them and asking for access now. (*This is not a garuanteed dataset*)\
The types of variables include Country of Origin, Date of Birth, Sociodemographics, Immigration History, Economic Credentials, Language Skills, Integration Status.\
There's not a lot of missing data in the dataset from what I've read from the paper.\

Overview of research question:\
\
I'm interested in predicting the naturalisation result for each immigrant with different backgrounds. My outcome variable will be categorical, which is that whether the immigrants will be voted "yes" through referendums. From reading the paper, the most useful predictors are country of origin and language skills. The goal of my model is predictive.\

Timeline:\
\
I'm still in contact with the Statistics Office in Switzerland, and I'm hoping to hearing back from them early next week. If I can get the data, I'll begin my EDA probably later next week, but if I can't, I need to choose an alternative dataset and have a clear idea of what I want to do with the dataset by the end of next week. I have not started planning the timeline for the rest of the quarter yet, but I think I'm able to do so next time when updating the data memo. \
