---
title: "pstat131_datamemo_updated"
author: "Sissi Shen"
date: "2022-10-18"
output: html_document
---

Overview of the dataset: \
Since I was not able to get access to the dataset that I mentioned last time in my data memo, I spent several weeks discovering new datasets and decided to use another dataset that allows me to predict the natives' hostility toward refugees. The paper related to this dataset exploits a natural experiment in the Aegean Sea, where Greek islands close to the Turkish coast experienced a sudden and massive increase in refugee arrivals while similar islands slightly farther away did not. They leveraged a targeted survey of 2,070 islands residents and distance to Turkey as an instrument and found that direct exposure to refugee arrivals induces sizeable and lasting increases in natives' hostility toward refugee, immigrant and Muslim minorities. \
A replication of their dataset can be found on Harvard Dataverse here:\
https://doi.org/10.7910/DVN/XGVQDT \
There are 12314 observations and all of them numeric variables (the categorical variable Gender has already been dummy coded). There's no missing data. \
\
Overview of the research question: \
I'm interested in predicting the level of hostility. I'm planning on calculating this variable using the five measurements in the datset: (1) whether they agreed that refugee children should be banned from schools (from 1 to 5); (2) whether Greece should decrease the number of people to whom it grants asylum (1–5); (3) whether asylum seekers are more likely to commit terrorist attacks (1–5) and (4) crimes (1–5) and (5) are a burden on the country (1–5). I plan on adding the scores up and using the final combined score as the outcome variable for the level of hostility. \
This question will be best answered with a regression approach. \
The predictors that I use are: gender(dummy), age, education level, household finance, tourismimpact (whether the income is dependent on tourism (from 1-5)), pastvote (measures respondents' political perference), self-placement on left-right axis, distance to Turkish coast, log distance, wethere there's an arrival of refugees on the island (dummy), numbers of arrival per capita. I think self-placement on left-right axis, distance to Turkish coast/log distance, and numbers of arrival per capita will be especially useful. The goal of my model will be predictive. \
\
Timeline:\
As I've already retreived the dataset, I plan on finishing the data cleaning and data split this week. I can also start working on the introduction and EDA next week. The actual model building process will come later in the quarter. \